version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/faststory
permissions:
  - object: /var/www/html/faststory/logs
    owner: root
    group: root
    mode: 777
    type:
      - directory
